// Generated by gencpp from file common_srvs/ConeMap.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_CONEMAP_H
#define COMMON_SRVS_MESSAGE_CONEMAP_H

#include <ros/service_traits.h>


#include <common_srvs/ConeMapRequest.h>
#include <common_srvs/ConeMapResponse.h>


namespace common_srvs
{

struct ConeMap
{

typedef ConeMapRequest Request;
typedef ConeMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConeMap
} // namespace common_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_srvs::ConeMap > {
  static const char* value()
  {
    return "b7e5900e2ea08a404fe38a8b59685279";
  }

  static const char* value(const ::common_srvs::ConeMap&) { return value(); }
};

template<>
struct DataType< ::common_srvs::ConeMap > {
  static const char* value()
  {
    return "common_srvs/ConeMap";
  }

  static const char* value(const ::common_srvs::ConeMap&) { return value(); }
};


// service_traits::MD5Sum< ::common_srvs::ConeMapRequest> should match 
// service_traits::MD5Sum< ::common_srvs::ConeMap > 
template<>
struct MD5Sum< ::common_srvs::ConeMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::ConeMap >::value();
  }
  static const char* value(const ::common_srvs::ConeMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::ConeMapRequest> should match 
// service_traits::DataType< ::common_srvs::ConeMap > 
template<>
struct DataType< ::common_srvs::ConeMapRequest>
{
  static const char* value()
  {
    return DataType< ::common_srvs::ConeMap >::value();
  }
  static const char* value(const ::common_srvs::ConeMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_srvs::ConeMapResponse> should match 
// service_traits::MD5Sum< ::common_srvs::ConeMap > 
template<>
struct MD5Sum< ::common_srvs::ConeMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::ConeMap >::value();
  }
  static const char* value(const ::common_srvs::ConeMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::ConeMapResponse> should match 
// service_traits::DataType< ::common_srvs::ConeMap > 
template<>
struct DataType< ::common_srvs::ConeMapResponse>
{
  static const char* value()
  {
    return DataType< ::common_srvs::ConeMap >::value();
  }
  static const char* value(const ::common_srvs::ConeMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_CONEMAP_H
