// Generated by gencpp from file common_srvs/Path.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_PATH_H
#define COMMON_SRVS_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <common_srvs/PathRequest.h>
#include <common_srvs/PathResponse.h>


namespace common_srvs
{

struct Path
{

typedef PathRequest Request;
typedef PathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Path
} // namespace common_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_srvs::Path > {
  static const char* value()
  {
    return "3fb3f9dacc279b964c4c8341122c34df";
  }

  static const char* value(const ::common_srvs::Path&) { return value(); }
};

template<>
struct DataType< ::common_srvs::Path > {
  static const char* value()
  {
    return "common_srvs/Path";
  }

  static const char* value(const ::common_srvs::Path&) { return value(); }
};


// service_traits::MD5Sum< ::common_srvs::PathRequest> should match 
// service_traits::MD5Sum< ::common_srvs::Path > 
template<>
struct MD5Sum< ::common_srvs::PathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::Path >::value();
  }
  static const char* value(const ::common_srvs::PathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::PathRequest> should match 
// service_traits::DataType< ::common_srvs::Path > 
template<>
struct DataType< ::common_srvs::PathRequest>
{
  static const char* value()
  {
    return DataType< ::common_srvs::Path >::value();
  }
  static const char* value(const ::common_srvs::PathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_srvs::PathResponse> should match 
// service_traits::MD5Sum< ::common_srvs::Path > 
template<>
struct MD5Sum< ::common_srvs::PathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::Path >::value();
  }
  static const char* value(const ::common_srvs::PathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::PathResponse> should match 
// service_traits::DataType< ::common_srvs::Path > 
template<>
struct DataType< ::common_srvs::PathResponse>
{
  static const char* value()
  {
    return DataType< ::common_srvs::Path >::value();
  }
  static const char* value(const ::common_srvs::PathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_PATH_H
