// Generated by gencpp from file common_msgs/PIDDebug.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_PIDDEBUG_H
#define COMMON_MSGS_MESSAGE_PIDDEBUG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct PIDDebug_
{
  typedef PIDDebug_<ContainerAllocator> Type;

  PIDDebug_()
    : point_following()  {
    }
  PIDDebug_(const ContainerAllocator& _alloc)
    : point_following(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_following_type;
  _point_following_type point_following;





  typedef boost::shared_ptr< ::common_msgs::PIDDebug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::PIDDebug_<ContainerAllocator> const> ConstPtr;

}; // struct PIDDebug_

typedef ::common_msgs::PIDDebug_<std::allocator<void> > PIDDebug;

typedef boost::shared_ptr< ::common_msgs::PIDDebug > PIDDebugPtr;
typedef boost::shared_ptr< ::common_msgs::PIDDebug const> PIDDebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::PIDDebug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::PIDDebug_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'common_msgs': ['/home/aaron/AutonomousRC/catkin_ws/src/common/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::PIDDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::PIDDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::PIDDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::PIDDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::PIDDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::PIDDebug_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::PIDDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acbcde480248f453332a6d1026e2caff";
  }

  static const char* value(const ::common_msgs::PIDDebug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacbcde480248f453ULL;
  static const uint64_t static_value2 = 0x332a6d1026e2caffULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::PIDDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/PIDDebug";
  }

  static const char* value(const ::common_msgs::PIDDebug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::PIDDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point point_following\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::common_msgs::PIDDebug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::PIDDebug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point_following);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDDebug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::PIDDebug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::PIDDebug_<ContainerAllocator>& v)
  {
    s << indent << "point_following: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point_following);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_PIDDEBUG_H
